
#-----------------------------------数据库配置----------------------------------------
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:/Users/straycamel/alibaba-inc/idea-workspace/BotApi/demo2.db
spring.datasource.username=
spring.datasource.password=

#数据库1的配置
spring.datasource.test1.driver-class-name = org.sqlite.JDBC
spring.datasource.test1.jdbc-url=jdbc:sqlite:/Users/straycamel/alibaba-inc/idea-workspace/BotApi/demo2.db
spring.datasource.test1.username =
spring.datasource.test1.password = 