

server.port=8080
#-----------------------------------数据库配置----------------------------------------
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:/Users/straycamel/alibaba-inc/idea-workspace/BotApi/demo.db
spring.datasource.username=
spring.datasource.password=
#------------------------------------redis配置---------------------------------------
